### ISSUE TITLE
Name not cool enough

### ISSUE THREAD

**Issue by vpnguy** [byt3bl33d3r/DeathStar#1]
DeathStar is so overplayed and honestly it doesnt even destroy worlds or solar systems. I suggest a more fitting name?

**Comment by byt3bl33d3r** [comment]
I am so glad this is the first issue ticket of this repo

**Comment by vpnguy** [comment]
Is that a WontFix?

**Comment by byt3bl33d3r** [comment]
it is now

**Comment by hatredshapedlikeaman** [comment]
This is a reoccurring issue. Please reconsider the "WontFix".  Think of the children.

**Comment by byt3bl33d3r** [comment]
babies are gross anyway. they won't mind.
