### ISSUE TITLE
Agents not connecting

### ISSUE THREAD

**Issue by c0d3xpl0it** [byt3bl33d3r/DeathStar#10]
I have successfully installed the forked Empire and Deathstar on Kali rolling 2017 VM.

Once I generate the powershell code using "launcher powershell DeathStar" and paste same to any of my windows machine. I dont get any agent connect back. Can you help ?

**Comment by byt3bl33d3r** [comment]
Did you setup the listener correctly? Can you paste listener settings?
Thanks

**Comment by c0d3xpl0it** [comment]
Please find the settings

![image](https://cloud.githubusercontent.com/assets/8144002/26733879/df6a807c-47c4-11e7-8b92-6e52a6d05e5d.png)

**Comment by c0d3xpl0it** [comment]
I gotcha the error. Thanx for awesome *TOOLS*

Love for **CrackMapExec** and now **DEATHSTAR** !!

**Comment by byt3bl33d3r** [comment]
glad you figured it out yourself 👍

**Comment by avantasia** [comment]
Any help for others with the same problem?

**Comment by jesusmmago** [comment]
c0d3xpl0it, could you explain what was the solution for you?

**Comment by c0d3xpl0it** [comment]
Better switch to new Empire 2.1 [https://twitter.com/byt3bl33d3r/status/902186832565329920](url)

**Comment by jesusmmago** [comment]
Nice, thanks!

**Comment by vinnytroia** [comment]
what was the solution? I am having the same issue again
