### ISSUE TITLE
DeathStar Dies on New Agent

### ISSUE THREAD

**Issue by Ike-Clinton** [byt3bl33d3r/DeathStar#14]
I'm trying to setup the following on a test network as per your tutorials on your site:
https://byt3bl33d3r.github.io/practical-guide-to-ntlm-relaying-in-2017-aka-getting-a-foothold-in-under-5-minutes.html

PLUS

https://byt3bl33d3r.github.io/automating-the-empire-with-the-death-star-getting-domain-admin-with-a-push-of-a-button.html

My setup:
1. python Responder.py -d -r -f -w -F -P -I eth0
2. ntlmrelayx -tf targets.txt -c "powershell -noP -sta -w 1 -enc powershell code here"
3. ./empire --rest --username username --password password
4. ./Deathstar.py -u username -p password

I can get a new agent by copying in the DeathStar launcher powershell command, and Deathstar sees the new Agent but then it dies shortly thereafter. Error message posted below.

``[+] New Agent => Name: BDHZE51L IP: 1.2.3.4 HostName: SB-W7-2 UserName: REDACTED HighIntegrity: 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 538, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 364, in get_loggedon
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_loggedon', agent_name, module_options)
  File "./DeathStar.py", line 170, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'
``

Any idea what the issue could be? After that error Empire just hangs and doesn't do anything else.

Target is a Windows 7 Enterprise machine.

**Comment by byt3bl33d3r** [comment]
You don't seem to be using my fork of empire as it says in the README.

**Comment by byt3bl33d3r** [comment]
Edit: the PR i mentioned has been merged but the changes haven't been pushed to the master branch.
So you can now either use Empire's dev branch or my fork.
Cheers

**Comment by Ike-Clinton** [comment]
Gah! You're right. I should have RTFM more. Thanks much.
