### ISSUE TITLE
Use SID instead of hardcoded name

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [byt3bl33d3r/DeathStar#18]
Hi!

Because of hardcoded group names such as "Domain Admins", DeathStar is not working on domains which are installed in another language. On the following screen-shot, the target domain is installed in french, thus "Domain Admins" is not an existing group (on french DC the group is called "Administrateurs de Domaine").

![deathstarcensored](https://user-images.githubusercontent.com/18633286/27049287-2d0690c2-4faf-11e7-9aa8-738b27d7ac3b.png)

I think the best solution is to use SID instead ([example with pywerview](https://github.com/the-useless-one/pywerview/blob/develop/pywerview/functions/net.py#L330-L335)). Unfortunately, I don't have time to PR, but I think the fix is quite simple with the Powerview' modules.

Anyway, great idea and great tool, you rock! :smiley: 

TPWSOS

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
My bad, in my case, the DC was installed in English but the user for the agent YFSABWEZ was a name with non-ascii characters in it and Powerview is not compatible with such name. Launching the stager with a ascii only  login works perfectly. So it's more a Powerview bug than a Deathstar bug...
However, using SID is still a good idea to make DeathStar not language dependent. Empire doesn't have Get-DomainSID module but the whole Powerview script is already included on the project, so you just have to write the python part, PR and voilà ! :)

TPWSOS

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
I've just found time to PR Empire to add Get-DomainSID module.
See [#606](https://github.com/EmpireProject/Empire/pull/606).

TPWSOS :sunflower:

**Comment by byt3bl33d3r** [comment]
Just FYI, waiting on https://github.com/EmpireProject/Empire/pull/657 to get merged, then will address this.

Thanks <3

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
Ha yes, I found the same problem (GroupName mandatory) but not i didn't have the time to PR. Good job too.

:sunflower:

**Comment by byt3bl33d3r** [comment]
Done!
Thanks again

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Good work !
:sunflower:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
The `user_hunter` function is still using an harcoded name for the domain admins group's name.

https://github.com/byt3bl33d3r/DeathStar/blob/5f93ba438700ebc4605f6c72d00a16ab87f6e6e1/DeathStar.py#L264

However, as far as I know Powerview is not able to hunt based on a SID :disappointed:
