### ISSUE TITLE
running deathstar on nethunter, empire starts but deathstar fails

### ISSUE THREAD

**Issue by ghostdog3993** [byt3bl33d3r/DeathStar#22]
as i said in title empire starts, but deathstar fails.. 
![screenshot_2017-07-12-02-04-13 1](https://user-images.githubusercontent.com/18478268/28096120-b13c9fd6-66a6-11e7-8272-9465cc32aff9.png)
any clue or can i provide other information?

**Comment by Bry-fi** [comment]
Try rerunning and reinstalling with python3 and pip3

pip3 install -r requirements.txt

python Death*

**Comment by byt3bl33d3r** [comment]
@ghostdog3993 Deathstar is written in python 3. You're using pip2 to install it which is for Python 2. Running `pip3 install -r requirements.txt` should solve this.
