### ISSUE TITLE
Remove Empire fix pull request from readme

### ISSUE THREAD

**Issue by Jamie-** [byt3bl33d3r/DeathStar#25]
The empire fork to fix functionality this has (https://github.com/EmpireProject/Empire/pull/531) was merged on June 4th. The part of the readme specifying that fork needs to be used until the fork is merged can now be removed.

Just FYI.

Thanks!

**Comment by Jamie-** [comment]
I don't think it's been merged to master yet actually but you can use 'dev' as it has been merged there

**Comment by byt3bl33d3r** [comment]
I'm currently waiting for the changes to be merged in the master branch, feel like it would be confusing for a lot of people otherwise :)

Thanks though
