### ISSUE TITLE
Connection Error. Check Empire RESTful API

### ISSUE THREAD

**Issue by kofx2002** [byt3bl33d3r/DeathStar#32]
[*] Powering up the Death Star
[-] Connection Error. Check Empire RESTful API
Linux KoF 4.11.0-kali1-amd64 #1 SMP Debian 4.11.6-1kali1 (2017-06-21) x86_64 GNU/Linux

i have this issue in kali linux

**Comment by Themercee** [comment]
Same here, doesnt seems to work :/

**Comment by DanMcInerney** [comment]
I might've fixed this with the pull request I just made. If you pull out the connection code or modify the code to not hide the exception we can give better answers as to what's going wrong. For me it was an exception saying SSL version too low.

Try my fork at https://github.com/DanMcInerney/DeathStar

**Comment by DanMcInerney** [comment]
Additionally you'll need to revert empire to a previous version with:

Solution:
cd Empire/
git reset --hard 2677363e508c81834b27c31ae534a5474d37eda5

**Comment by byt3bl33d3r** [comment]
This is probably related to #29 and/or #28. Closing since it's a duplicate.
