### ISSUE TITLE
ImportError: No module named 'IPython'

### ISSUE THREAD

**Issue by nem0n** [byt3bl33d3r/DeathStar#40]
Hi,

Today when I cloned the project and try to run I get this error, by the way, I am using Kali,
To solve the problem I tried
===========
`pip install ipython`
`pip install scipy`

But none of them solved problem, after a quick research I found the solution for it which is 

`sudo pip 3 install jupyter`

And wanted to help if anyone having this issue, can try it

**Comment by byt3bl33d3r** [comment]
My bad, forgot to remove that before pushing some changes. Just pushed a fix.

Cheers
