### ISSUE TITLE
Deathstar and Empire

### ISSUE THREAD

**Issue by securityhawk** [byt3bl33d3r/DeathStar#43]
Hey Guys

Newbie here so apologies ;) 

When I run Empire, the Empire console launches, therefore I can't run Deathstar until I have quit Empire.

My questions is how do I launch Deathstar once I am at the Empire> prompt?  

I have tried running Empire in --headless but that doesn't give a command prompt.

I am running Ubuntu 16.04

Thanks for any advice and merry Christmas!

**Comment by utkusen** [comment]
you need to run the deathstar in different terminal. If you are connected a remote server with ssh, you can use `screen` command to run empire in background

**Comment by securityhawk** [comment]
Perfect, thank you all working - thanks again!
