### ISSUE TITLE
Question Re Agent Execution

### ISSUE THREAD

**Issue by securityhawk** [byt3bl33d3r/DeathStar#45]
Hi Guys

I have successfully deployed my first agent on my lab, it has got to "Executed Mimikatz' and is not progressing.

The question is do I leave it or has this finished the processes it has and needs to be terminated? 

Thanks

Phil

**Comment by utkusen** [comment]
It also happens to me. That's why I'm runnig deathstar with a timeout in case it's stuck. For example `timeout 300 python3 deathstar.py` this will terminate deathstar after 300 seconds

**Comment by securityhawk** [comment]
Ahhh ok thanks @utkusen
