### ISSUE TITLE
Empire 2.4 and DeathStar

### ISSUE THREAD

**Issue by securityhawk** [byt3bl33d3r/DeathStar#46]
Hi Guys

I am trying to get the DeathStar listener working with Empire 2.4 but despite both installing fine, the stagers will not communicate.

I am running Empire 2.3 on another VPS and this is working perfectly.

Anybody else experiencing this issue?

Thanks

Phil

**Comment by byt3bl33d3r** [comment]
@securityhawk from the way you're describing this, this seems to be a problem with Empire not Deathstar. You should probably open an Issue ticket on their repo.

Closing.
