### ISSUE TITLE
Where to put DeathStar folder?

### ISSUE THREAD

**Issue by alisonliu** [byt3bl33d3r/DeathStar#47]
Where to put DeathStar folder? It complains about couldn't find powershell modules and it just hangs upon getting a new agent. I put DeathStar folder and Empire both under /opt

<img width="791" alt="just hangs" src="https://user-images.githubusercontent.com/22718011/34912927-f4436ba0-f8a2-11e7-8cfd-7fd9236814a1.png">

**Comment by Chiggins** [comment]
I'm having the same issue, though I know it's not because of the location of the DeathStar/Empire folders. Running on an up to date Kali Linux install with fresh `git clone` of both DeathStar and Empire.

**Comment by Chiggins** [comment]
Just as a debugging step, I went as far back as https://github.com/EmpireProject/Empire/commit/a0234bd195f4f69ba2137b6372eadcb9602311c9 and still was getting the same error.

**Comment by DanMcInerney** [comment]
This is fixed in my PR

**Comment by byt3bl33d3r** [comment]
Resolved in #50.

Closing
