### ISSUE TITLE
It's threaded but doesn't seem to be working in parallel

### ISSUE THREAD

**Issue by DanMcInerney** [byt3bl33d3r/DeathStar#52]
It seems like the pwn_the_shit_outta_everything function is just performing its duties as if it weren't multithreaded at all. It hits the spread_threads then those threads take control and do their thing while pwn_the_shit_outta_everything seems to wait and not move on. It doesn't seem like blocking code though from looking at it. Any idea if I'm just imagining things?

**Comment by byt3bl33d3r** [comment]
I noticed this to. The only explanation I have is that somewhere along the line blocking calls are being made. Hence why I sorta want to rewrite the whole thing using asyncio. 

I might just do that now since you fixed everything lol
