### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 2, got 1)

### ISSUE THREAD

**Issue by DigitalCorrosion** [byt3bl33d3r/DeathStar#56]
I use to not get this as much but now it is quite persistent.

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 620, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 404, in get_loggedon
    username, domain, *_ = entry.split()
ValueError: not enough values to unpack (expected at least 2, got 1)

**Comment by LordWeeble** [comment]
I am also getting this error very often and I am using the Forked version and the Original most up to date version of Empire any fixes?

**Comment by LordWeeble** [comment]
Also, I have /usr/lib/python3.6/threading.py so not 3.5...

**Comment by byt3bl33d3r** [comment]
Development on this project is at a stand still because of all the breaking changes Empire has made to it's API and modules over the past year and I don't have time to keep fixing them.

The goal is going to be to re-write this to use [SILENTTRINITY](https://github.com/byt3bl33d3r/SILENTTRINITY), that way I have control over both projects, however that will take time as to do that I'm going to need to write a Rest-API and all of the necessary modules.

**Comment by True-Demon** [comment]
> Development on this project is at a stand still because of all the breaking changes Empire has made to it's API and modules over the past year and I don't have time to keep fixing them.
> 
> The goal is going to be to re-write this to use [SILENTTRINITY](https://github.com/byt3bl33d3r/SILENTTRINITY), that way I have control over both projects, however that will take time as to do that I'm going to need to write a Rest-API and all of the necessary modules.

Explains why I'm getting stacktraces all over the place, lol. Might be worthwhile to put an update in the README.md that this is what is going on and make a general call for PRs to help fix the API. This tool is extremely helpful, especially when attacking a huge environment that's so easy to get lost in. I'd be willing to donate some time to helping work out the bugs if it's worthwhile and you still plan on maintaining DeathStar in the future. Keep us posted, homie. :+1:
