### ISSUE TITLE
Powershell through CME

### ISSUE THREAD

**Issue by bucky67gto** [byt3bl33d3r/DeathStar#66]
Can you send the powershell command through CME?  I have tried:

cme smb 10.10.10.10 -u test -p test -X powershell -noP -sta -w 1 -enc then-a-long-list-of-characters-i-copied-from-empire-after-generating-them-from-the-listener-application

looks like it may run, but never returns an agent.....thoughts?

thanks fro the great tools

**Comment by byt3bl33d3r** [comment]
Think you opened this issue in the wrong repo...

FYI https://github.com/byt3bl33d3r/CrackMapExec/wiki/Command-Execution
