### ISSUE TITLE
"BLANK" credentials being used to laterally spread with GPP privesc

### ISSUE THREAD

**Issue by stboch** [byt3bl33d3r/DeathStar#9]
GPP Yielded hundreds of "BLANK" and is wasting time trying to spread laterally using .\BLANK

**Comment by byt3bl33d3r** [comment]
Huh , interesting. Could you give me the raw output of the privesc/gpp module?
Thanks

**Comment by stboch** [comment]
Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\User\Preferences\Drives\Drives.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\User\Preferences\Printers\Printers.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\User\Preferences\Drives\Drives.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\Machine\Preferences\Groups\Groups.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\User\Preferences\Drives\Drives.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{BGUID}\User\Preferences\Drives\Drives.xml

Changed   : [BLANK]
UserNames : [BLANK]
NewName   : [BLANK]
Passwords : [BLANK]
File      : \\DC1.AD.Local\SYSVOL\AD.Local\Policies\{GUID}\User\Preferences\Drives\Drives.xml
`

**Comment by byt3bl33d3r** [comment]
Ok , well that shoulnd't be hard to fix. Will take care of this when I get home.
Cheers

**Comment by byt3bl33d3r** [comment]
https://github.com/byt3bl33d3r/DeathStar/commit/c305aadb7ce78fac20a30187c82c9d579348b014 should have fixed this. Re-open otherwise.
